// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package sqlitegen

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO board (id, workspace_id, project_id, name, position, version, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, 1, ?6, ?7)
RETURNING id, workspace_id, project_id, name, position, version, archived_at, created_at, updated_at
`

type CreateBoardParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Name        string
	Position    string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO board_column (id, workspace_id, board_id, name, position, category, version, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, 1, ?7, ?8)
RETURNING id, workspace_id, board_id, name, position, category, wip_limit, version, archived_at, created_at, updated_at
`

type CreateColumnParams struct {
	ID          string
	WorkspaceID string
	BoardID     string
	Name        string
	Position    string
	Category    string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error) {
	row := q.db.QueryRowContext(ctx, createColumn,
		arg.ID,
		arg.WorkspaceID,
		arg.BoardID,
		arg.Name,
		arg.Position,
		arg.Category,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.Category,
		&i.WipLimit,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoard = `-- name: GetBoard :one
SELECT id, workspace_id, project_id, name, position, version, archived_at, created_at, updated_at FROM board WHERE id = ?1 AND workspace_id = ?2
`

type GetBoardParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetBoard(ctx context.Context, arg GetBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoard, arg.ID, arg.WorkspaceID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBoardByProject = `-- name: GetBoardByProject :one
SELECT id, workspace_id, project_id, name, position, version, archived_at, created_at, updated_at FROM board WHERE project_id = ?1 AND workspace_id = ?2 AND archived_at IS NULL ORDER BY position LIMIT 1
`

type GetBoardByProjectParams struct {
	ProjectID   string
	WorkspaceID string
}

func (q *Queries) GetBoardByProject(ctx context.Context, arg GetBoardByProjectParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoardByProject, arg.ProjectID, arg.WorkspaceID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColumn = `-- name: GetColumn :one
SELECT id, workspace_id, board_id, name, position, category, wip_limit, version, archived_at, created_at, updated_at FROM board_column WHERE id = ?1 AND workspace_id = ?2
`

type GetColumnParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetColumn(ctx context.Context, arg GetColumnParams) (BoardColumn, error) {
	row := q.db.QueryRowContext(ctx, getColumn, arg.ID, arg.WorkspaceID)
	var i BoardColumn
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.BoardID,
		&i.Name,
		&i.Position,
		&i.Category,
		&i.WipLimit,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listColumns = `-- name: ListColumns :many
SELECT id, workspace_id, board_id, name, position, category, wip_limit, version, archived_at, created_at, updated_at FROM board_column WHERE board_id = ?1 AND workspace_id = ?2 AND archived_at IS NULL ORDER BY position
`

type ListColumnsParams struct {
	BoardID     string
	WorkspaceID string
}

func (q *Queries) ListColumns(ctx context.Context, arg ListColumnsParams) ([]BoardColumn, error) {
	rows, err := q.db.QueryContext(ctx, listColumns, arg.BoardID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardColumn{}
	for rows.Next() {
		var i BoardColumn
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.BoardID,
			&i.Name,
			&i.Position,
			&i.Category,
			&i.WipLimit,
			&i.Version,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
