// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO event (id, workspace_id, project_id, board_id, card_id, seq, actor_user_id, via_token_id, actor_kind, kind, payload, occurred_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12)
`

type InsertEventParams struct {
	ID          string
	WorkspaceID string
	ProjectID   sql.NullString
	BoardID     sql.NullString
	CardID      sql.NullString
	Seq         int64
	ActorUserID sql.NullString
	ViaTokenID  sql.NullString
	ActorKind   string
	Kind        string
	Payload     string
	OccurredAt  int64
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.BoardID,
		arg.CardID,
		arg.Seq,
		arg.ActorUserID,
		arg.ViaTokenID,
		arg.ActorKind,
		arg.Kind,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listEventsByCard = `-- name: ListEventsByCard :many
SELECT id, workspace_id, project_id, board_id, card_id, seq, actor_user_id, via_token_id, actor_kind, kind, payload, occurred_at FROM event WHERE card_id = ?1 AND workspace_id = ?2 ORDER BY seq DESC LIMIT CAST(?3 AS BIGINT)
`

type ListEventsByCardParams struct {
	CardID      sql.NullString
	WorkspaceID string
	Lim         int64
}

func (q *Queries) ListEventsByCard(ctx context.Context, arg ListEventsByCardParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByCard, arg.CardID, arg.WorkspaceID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.BoardID,
			&i.CardID,
			&i.Seq,
			&i.ActorUserID,
			&i.ViaTokenID,
			&i.ActorKind,
			&i.Kind,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsSince = `-- name: ListEventsSince :many
SELECT id, workspace_id, project_id, board_id, card_id, seq, actor_user_id, via_token_id, actor_kind, kind, payload, occurred_at FROM event WHERE workspace_id = ?1 AND seq > ?2 ORDER BY seq LIMIT CAST(?3 AS BIGINT)
`

type ListEventsSinceParams struct {
	WorkspaceID string
	Seq         int64
	Lim         int64
}

func (q *Queries) ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsSince, arg.WorkspaceID, arg.Seq, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.BoardID,
			&i.CardID,
			&i.Seq,
			&i.ActorUserID,
			&i.ViaTokenID,
			&i.ActorKind,
			&i.Kind,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
