// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const completeJob = `-- name: CompleteJob :exec
UPDATE job SET state = 'done', completed_at = ?1, lease_owner = NULL, lease_expires_at = NULL
WHERE id = ?2 AND state = 'leased' AND lease_owner = ?3
`

type CompleteJobParams struct {
	CompletedAt sql.NullInt64
	ID          string
	Owner       sql.NullString
}

// CompleteJob releases the lease only while this owner still holds it. A
// runner whose lease expired, and whose job another runner has already
// reclaimed, must not clobber the new owner's outcome: the update matches
// no row instead. RetryJob and DeadJob carry the same guard.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.CompletedAt, arg.ID, arg.Owner)
	return err
}

const countQueuedJobs = `-- name: CountQueuedJobs :one
SELECT count(*) FROM job WHERE kind = ?1 AND payload = ?2 AND state = 'queued'
`

type CountQueuedJobsParams struct {
	Kind    string
	Payload string
}

// CountQueuedJobs reports how many jobs with this kind and payload are
// still waiting to run. An enqueuer whose job is idempotent in its
// payload calls it inside its own transaction to skip a duplicate.
func (q *Queries) CountQueuedJobs(ctx context.Context, arg CountQueuedJobsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueuedJobs, arg.Kind, arg.Payload)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deadJob = `-- name: DeadJob :exec
UPDATE job SET state = 'dead', completed_at = ?1, last_error = ?2, lease_owner = NULL, lease_expires_at = NULL
WHERE id = ?3 AND state = 'leased' AND lease_owner = ?4
`

type DeadJobParams struct {
	CompletedAt sql.NullInt64
	LastError   sql.NullString
	ID          string
	Owner       sql.NullString
}

// DeadJob is guarded by the lease owner; see CompleteJob.
func (q *Queries) DeadJob(ctx context.Context, arg DeadJobParams) error {
	_, err := q.db.ExecContext(ctx, deadJob,
		arg.CompletedAt,
		arg.LastError,
		arg.ID,
		arg.Owner,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, workspace_id, kind, payload, state, attempts, max_attempts, run_at, lease_owner, lease_expires_at, last_error, created_at, completed_at FROM job WHERE id = ?1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAt,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :exec
INSERT INTO job (id, workspace_id, kind, payload, state, attempts, max_attempts, run_at, created_at)
VALUES (?1, ?2, ?3, ?4, 'queued', 0, ?5, ?6, ?7)
`

type InsertJobParams struct {
	ID          string
	WorkspaceID sql.NullString
	Kind        string
	Payload     string
	MaxAttempts int64
	RunAt       int64
	CreatedAt   int64
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) error {
	_, err := q.db.ExecContext(ctx, insertJob,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Payload,
		arg.MaxAttempts,
		arg.RunAt,
		arg.CreatedAt,
	)
	return err
}

const leaseJobs = `-- name: LeaseJobs :many
UPDATE job SET state = 'leased', lease_owner = ?1, lease_expires_at = ?2, attempts = attempts + 1
WHERE id IN (
    SELECT id FROM job AS j
    WHERE (j.state = 'queued' AND j.run_at <= ?3) OR (j.state = 'leased' AND j.lease_expires_at < ?4)
    ORDER BY j.run_at, j.id
    LIMIT CAST(?5 AS BIGINT)
)
RETURNING id, workspace_id, kind, payload, state, attempts, max_attempts, run_at, lease_owner, lease_expires_at, last_error, created_at, completed_at
`

type LeaseJobsParams struct {
	Owner      sql.NullString
	LeaseUntil sql.NullInt64
	NowQueued  int64
	NowLeased  sql.NullInt64
	Batch      int64
}

func (q *Queries) LeaseJobs(ctx context.Context, arg LeaseJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, leaseJobs,
		arg.Owner,
		arg.LeaseUntil,
		arg.NowQueued,
		arg.NowLeased,
		arg.Batch,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByState = `-- name: ListJobsByState :many
SELECT id, workspace_id, kind, payload, state, attempts, max_attempts, run_at, lease_owner, lease_expires_at, last_error, created_at, completed_at FROM job WHERE state = ?1 ORDER BY created_at LIMIT CAST(?2 AS BIGINT)
`

type ListJobsByStateParams struct {
	State string
	Lim   int64
}

func (q *Queries) ListJobsByState(ctx context.Context, arg ListJobsByStateParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByState, arg.State, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Payload,
			&i.State,
			&i.Attempts,
			&i.MaxAttempts,
			&i.RunAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseJob = `-- name: ReleaseJob :exec
UPDATE job SET state = 'queued', run_at = ?1, attempts = ?2, lease_owner = NULL, lease_expires_at = NULL
WHERE id = ?3 AND state = 'leased' AND lease_owner = ?4
`

type ReleaseJobParams struct {
	RunAt    int64
	Attempts int64
	ID       string
	Owner    sql.NullString
}

// ReleaseJob puts a leased job back in the queue exactly as it was found:
// the same run_at and the same attempt count, undoing the increment
// LeaseJobs made. The runner uses it when its context is cancelled while
// a handler runs, so a shutdown neither burns an attempt nor leaves the
// row leased for the rest of the lease. Guarded by the lease owner; see
// CompleteJob.
func (q *Queries) ReleaseJob(ctx context.Context, arg ReleaseJobParams) error {
	_, err := q.db.ExecContext(ctx, releaseJob,
		arg.RunAt,
		arg.Attempts,
		arg.ID,
		arg.Owner,
	)
	return err
}

const retryJob = `-- name: RetryJob :exec
UPDATE job SET state = 'queued', run_at = ?1, last_error = ?2, lease_owner = NULL, lease_expires_at = NULL
WHERE id = ?3 AND state = 'leased' AND lease_owner = ?4
`

type RetryJobParams struct {
	RunAt     int64
	LastError sql.NullString
	ID        string
	Owner     sql.NullString
}

// RetryJob is guarded by the lease owner; see CompleteJob.
func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) error {
	_, err := q.db.ExecContext(ctx, retryJob,
		arg.RunAt,
		arg.LastError,
		arg.ID,
		arg.Owner,
	)
	return err
}
