// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"database/sql"
)

type AppUser struct {
	ID              string
	WorkspaceID     string
	Email           sql.NullString
	Name            string
	Kind            string
	PasswordHash    sql.NullString
	EmailVerifiedAt sql.NullInt64
	Locale          string
	DisabledAt      sql.NullInt64
	DeletedAt       sql.NullInt64
	AnonymizedAt    sql.NullInt64
	CreatedAt       int64
	UpdatedAt       int64
}

type Board struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Name        string
	Position    string
	Version     int64
	ArchivedAt  sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

type BoardColumn struct {
	ID          string
	WorkspaceID string
	BoardID     string
	Name        string
	Position    string
	Category    string
	WipLimit    sql.NullInt64
	Version     int64
	ArchivedAt  sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

type Card struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	BoardID     string
	ColumnID    string
	Number      int64
	Title       string
	Description string
	Position    string
	DueDate     sql.NullInt64
	CreatedBy   string
	CompletedAt sql.NullInt64
	ArchivedAt  sql.NullInt64
	Version     int64
	TypeID      sql.NullString
	ParentID    sql.NullString
	Priority    sql.NullInt64
	Estimate    sql.NullFloat64
	StartDate   sql.NullInt64
	Resolution  sql.NullString
	IterationID sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

type CardAssignee struct {
	WorkspaceID string
	CardID      string
	UserID      string
}

type CardLabel struct {
	WorkspaceID string
	CardID      string
	LabelID     string
}

type CommandReceipt struct {
	WorkspaceID    sql.NullString
	IdempotencyKey string
	ActorID        string
	Result         string
	CreatedAt      int64
}

type Comment struct {
	ID          string
	WorkspaceID string
	CardID      string
	AuthorID    string
	Body        string
	ViaTokenID  sql.NullString
	EditedAt    sql.NullInt64
	DeletedAt   sql.NullInt64
	CreatedAt   int64
	UpdatedAt   int64
}

type Event struct {
	ID          string
	WorkspaceID string
	ProjectID   sql.NullString
	BoardID     sql.NullString
	CardID      sql.NullString
	Seq         int64
	ActorUserID sql.NullString
	ViaTokenID  sql.NullString
	ActorKind   string
	Kind        string
	Payload     string
	OccurredAt  int64
}

type Job struct {
	ID             string
	WorkspaceID    sql.NullString
	Kind           string
	Payload        string
	State          string
	Attempts       int64
	MaxAttempts    int64
	RunAt          int64
	LeaseOwner     sql.NullString
	LeaseExpiresAt sql.NullInt64
	LastError      sql.NullString
	CreatedAt      int64
	CompletedAt    sql.NullInt64
}

type Label struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Name        string
	Color       string
	Kind        string
	CreatedAt   int64
	UpdatedAt   int64
}

type Project struct {
	ID             string
	WorkspaceID    string
	Key            string
	Name           string
	NextCardNumber int64
	EstimateUnit   sql.NullString
	Version        int64
	ArchivedAt     sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
}

type ProjectKeyHistory struct {
	WorkspaceID string
	ProjectID   string
	OldKey      string
	ChangedAt   int64
}

type ProjectMember struct {
	WorkspaceID string
	ProjectID   string
	UserID      string
	Role        string
	CreatedAt   int64
}

type Workspace struct {
	ID        string
	Name      string
	Slug      string
	NextSeq   int64
	CreatedAt int64
	UpdatedAt int64
}

type WorkspaceMember struct {
	WorkspaceID string
	UserID      string
	Role        string
	CreatedAt   int64
}
