// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitegen

import (
	"context"
)

type Querier interface {
	AddCardAssignee(ctx context.Context, arg AddCardAssigneeParams) error
	AddCardLabel(ctx context.Context, arg AddCardLabelParams) error
	// CompleteJob releases the lease only while this owner still holds it. A
	// runner whose lease expired, and whose job another runner has already
	// reclaimed, must not clobber the new owner's outcome: the update matches
	// no row instead. RetryJob and DeadJob carry the same guard.
	CompleteJob(ctx context.Context, arg CompleteJobParams) error
	CountCardsInColumn(ctx context.Context, columnID string) (int64, error)
	// CountQueuedJobs reports how many jobs with this kind and payload are
	// still waiting to run. An enqueuer whose job is idempotent in its
	// payload calls it inside its own transaction to skip a duplicate.
	CountQueuedJobs(ctx context.Context, arg CountQueuedJobsParams) (int64, error)
	CountWorkspaces(ctx context.Context) (int64, error)
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateCard(ctx context.Context, arg CreateCardParams) (Card, error)
	CreateColumn(ctx context.Context, arg CreateColumnParams) (BoardColumn, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	// DeadJob is guarded by the lease owner; see CompleteJob.
	DeadJob(ctx context.Context, arg DeadJobParams) error
	DeleteReceiptsBefore(ctx context.Context, before int64) (int64, error)
	FirstPositionInColumn(ctx context.Context, columnID string) (string, error)
	GetBoard(ctx context.Context, id string) (Board, error)
	GetBoardByProject(ctx context.Context, projectID string) (Board, error)
	GetCard(ctx context.Context, id string) (Card, error)
	GetCardByNumber(ctx context.Context, arg GetCardByNumberParams) (Card, error)
	GetColumn(ctx context.Context, id string) (BoardColumn, error)
	GetJob(ctx context.Context, id string) (Job, error)
	GetLabel(ctx context.Context, id string) (Label, error)
	GetProject(ctx context.Context, id string) (Project, error)
	GetProjectByKey(ctx context.Context, arg GetProjectByKeyParams) (Project, error)
	GetReceipt(ctx context.Context, arg GetReceiptParams) (CommandReceipt, error)
	GetUser(ctx context.Context, id string) (AppUser, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (AppUser, error)
	GetWorkspace(ctx context.Context, id string) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	InsertJob(ctx context.Context, arg InsertJobParams) error
	InsertReceipt(ctx context.Context, arg InsertReceiptParams) error
	LastPositionInColumn(ctx context.Context, columnID string) (string, error)
	LeaseJobs(ctx context.Context, arg LeaseJobsParams) ([]Job, error)
	ListCardAssigneeIDs(ctx context.Context, cardID string) ([]string, error)
	ListCardLabelIDs(ctx context.Context, cardID string) ([]string, error)
	ListCardsByBoard(ctx context.Context, boardID string) ([]Card, error)
	ListCardsByColumn(ctx context.Context, columnID string) ([]Card, error)
	ListColumns(ctx context.Context, boardID string) ([]BoardColumn, error)
	ListComments(ctx context.Context, cardID string) ([]Comment, error)
	ListEventsByCard(ctx context.Context, arg ListEventsByCardParams) ([]Event, error)
	ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error)
	ListJobsByState(ctx context.Context, arg ListJobsByStateParams) ([]Job, error)
	ListLabels(ctx context.Context, projectID string) ([]Label, error)
	ListProjectMembers(ctx context.Context, projectID string) ([]ProjectMember, error)
	ListProjectMembershipsForUser(ctx context.Context, userID string) ([]ProjectMember, error)
	ListProjects(ctx context.Context, workspaceID string) ([]Project, error)
	// Every versioned update carries "AND version = @version": on Postgres
	// READ COMMITTED two transactions can both read version 1, so the check
	// must be in the UPDATE itself; zero rows means E_CONFLICT.
	MoveCard(ctx context.Context, arg MoveCardParams) (Card, error)
	NextCardNumber(ctx context.Context, arg NextCardNumberParams) (int64, error)
	NextPositionAfter(ctx context.Context, arg NextPositionAfterParams) (string, error)
	NextSeq(ctx context.Context, id string) (int64, error)
	PrevPositionBefore(ctx context.Context, arg PrevPositionBeforeParams) (string, error)
	RemoveCardAssignee(ctx context.Context, arg RemoveCardAssigneeParams) error
	RemoveCardLabel(ctx context.Context, arg RemoveCardLabelParams) error
	// RetryJob is guarded by the lease owner; see CompleteJob.
	RetryJob(ctx context.Context, arg RetryJobParams) error
	SetCardArchived(ctx context.Context, arg SetCardArchivedParams) (Card, error)
	TouchCard(ctx context.Context, arg TouchCardParams) (Card, error)
	UpdateCardFields(ctx context.Context, arg UpdateCardFieldsParams) (Card, error)
	UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) error
	UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) error
}

var _ Querier = (*Queries)(nil)
