// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt.sql

package sqlitegen

import (
	"context"
	"database/sql"
)

const deleteReceiptsBefore = `-- name: DeleteReceiptsBefore :execrows
DELETE FROM command_receipt WHERE created_at < ?1
`

func (q *Queries) DeleteReceiptsBefore(ctx context.Context, before int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteReceiptsBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getReceipt = `-- name: GetReceipt :one
SELECT workspace_id, idempotency_key, actor_id, result, created_at FROM command_receipt WHERE idempotency_key = ?1 AND actor_id = ?2
`

type GetReceiptParams struct {
	IdempotencyKey string
	ActorID        string
}

func (q *Queries) GetReceipt(ctx context.Context, arg GetReceiptParams) (CommandReceipt, error) {
	row := q.db.QueryRowContext(ctx, getReceipt, arg.IdempotencyKey, arg.ActorID)
	var i CommandReceipt
	err := row.Scan(
		&i.WorkspaceID,
		&i.IdempotencyKey,
		&i.ActorID,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const insertReceipt = `-- name: InsertReceipt :exec
INSERT INTO command_receipt (workspace_id, idempotency_key, actor_id, result, created_at)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertReceiptParams struct {
	WorkspaceID    sql.NullString
	IdempotencyKey string
	ActorID        string
	Result         string
	CreatedAt      int64
}

func (q *Queries) InsertReceipt(ctx context.Context, arg InsertReceiptParams) error {
	_, err := q.db.ExecContext(ctx, insertReceipt,
		arg.WorkspaceID,
		arg.IdempotencyKey,
		arg.ActorID,
		arg.Result,
		arg.CreatedAt,
	)
	return err
}
