// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package sqlitegen

import (
	"context"
)

const countWorkspaces = `-- name: CountWorkspaces :one
SELECT count(*) FROM workspace
`

func (q *Queries) CountWorkspaces(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspaces)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspace (id, name, slug, next_seq, created_at, updated_at)
VALUES (?1, ?2, ?3, 0, ?4, ?5)
RETURNING id, name, slug, next_seq, created_at, updated_at
`

type CreateWorkspaceParams struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.NextSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, slug, next_seq, created_at, updated_at FROM workspace WHERE id = ?1
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.NextSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, slug, next_seq, created_at, updated_at FROM workspace WHERE slug = ?1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.NextSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextSeq = `-- name: NextSeq :one
UPDATE workspace SET next_seq = next_seq + 1 WHERE id = ?1 RETURNING next_seq
`

func (q *Queries) NextSeq(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSeq, id)
	var next_seq int64
	err := row.Scan(&next_seq)
	return next_seq, err
}
