// Code generated by go run ./internal/gen; DO NOT EDIT.

package store

import (
	"context"
	"database/sql"

	"github.com/necrogami/kanboard/internal/server/store/pggen"
	"github.com/necrogami/kanboard/internal/server/store/sqlitegen"
)

var _ = sql.ErrNoRows

type pgQuerier struct{ q *pggen.Queries }

func newPGQuerier(db pggen.DBTX) Querier { return &pgQuerier{q: pggen.New(db)} }

func (a *pgQuerier) AddCardAssignee(ctx context.Context, arg sqlitegen.AddCardAssigneeParams) error {
	return a.q.AddCardAssignee(ctx, pggen.AddCardAssigneeParams(arg))
}

func (a *pgQuerier) AddCardLabel(ctx context.Context, arg sqlitegen.AddCardLabelParams) error {
	return a.q.AddCardLabel(ctx, pggen.AddCardLabelParams(arg))
}

func (a *pgQuerier) CompleteJob(ctx context.Context, arg sqlitegen.CompleteJobParams) error {
	return a.q.CompleteJob(ctx, pggen.CompleteJobParams(arg))
}

func (a *pgQuerier) CountCardsInColumn(ctx context.Context, arg string) (int64, error) {
	r, err := a.q.CountCardsInColumn(ctx, arg)
	return r, err
}

func (a *pgQuerier) CountQueuedJobs(ctx context.Context, arg sqlitegen.CountQueuedJobsParams) (int64, error) {
	r, err := a.q.CountQueuedJobs(ctx, pggen.CountQueuedJobsParams(arg))
	return r, err
}

func (a *pgQuerier) CountWorkspaces(ctx context.Context) (int64, error) {
	r, err := a.q.CountWorkspaces(ctx)
	return r, err
}

func (a *pgQuerier) CreateBoard(ctx context.Context, arg sqlitegen.CreateBoardParams) (sqlitegen.Board, error) {
	r, err := a.q.CreateBoard(ctx, pggen.CreateBoardParams(arg))
	return sqlitegen.Board(r), err
}

func (a *pgQuerier) CreateCard(ctx context.Context, arg sqlitegen.CreateCardParams) (sqlitegen.Card, error) {
	r, err := a.q.CreateCard(ctx, pggen.CreateCardParams(arg))
	return sqlitegen.Card(r), err
}

func (a *pgQuerier) CreateColumn(ctx context.Context, arg sqlitegen.CreateColumnParams) (sqlitegen.BoardColumn, error) {
	r, err := a.q.CreateColumn(ctx, pggen.CreateColumnParams(arg))
	return sqlitegen.BoardColumn(r), err
}

func (a *pgQuerier) CreateComment(ctx context.Context, arg sqlitegen.CreateCommentParams) (sqlitegen.Comment, error) {
	r, err := a.q.CreateComment(ctx, pggen.CreateCommentParams(arg))
	return sqlitegen.Comment(r), err
}

func (a *pgQuerier) CreateLabel(ctx context.Context, arg sqlitegen.CreateLabelParams) (sqlitegen.Label, error) {
	r, err := a.q.CreateLabel(ctx, pggen.CreateLabelParams(arg))
	return sqlitegen.Label(r), err
}

func (a *pgQuerier) CreateProject(ctx context.Context, arg sqlitegen.CreateProjectParams) (sqlitegen.Project, error) {
	r, err := a.q.CreateProject(ctx, pggen.CreateProjectParams(arg))
	return sqlitegen.Project(r), err
}

func (a *pgQuerier) CreateUser(ctx context.Context, arg sqlitegen.CreateUserParams) (sqlitegen.AppUser, error) {
	r, err := a.q.CreateUser(ctx, pggen.CreateUserParams(arg))
	return sqlitegen.AppUser(r), err
}

func (a *pgQuerier) CreateWorkspace(ctx context.Context, arg sqlitegen.CreateWorkspaceParams) (sqlitegen.Workspace, error) {
	r, err := a.q.CreateWorkspace(ctx, pggen.CreateWorkspaceParams(arg))
	return sqlitegen.Workspace(r), err
}

func (a *pgQuerier) DeadJob(ctx context.Context, arg sqlitegen.DeadJobParams) error {
	return a.q.DeadJob(ctx, pggen.DeadJobParams(arg))
}

func (a *pgQuerier) DeleteReceiptsBefore(ctx context.Context, arg int64) (int64, error) {
	r, err := a.q.DeleteReceiptsBefore(ctx, arg)
	return r, err
}

func (a *pgQuerier) FirstPositionInColumn(ctx context.Context, arg string) (string, error) {
	r, err := a.q.FirstPositionInColumn(ctx, arg)
	return r, err
}

func (a *pgQuerier) GetBoard(ctx context.Context, arg string) (sqlitegen.Board, error) {
	r, err := a.q.GetBoard(ctx, arg)
	return sqlitegen.Board(r), err
}

func (a *pgQuerier) GetBoardByProject(ctx context.Context, arg string) (sqlitegen.Board, error) {
	r, err := a.q.GetBoardByProject(ctx, arg)
	return sqlitegen.Board(r), err
}

func (a *pgQuerier) GetCard(ctx context.Context, arg string) (sqlitegen.Card, error) {
	r, err := a.q.GetCard(ctx, arg)
	return sqlitegen.Card(r), err
}

func (a *pgQuerier) GetCardByNumber(ctx context.Context, arg sqlitegen.GetCardByNumberParams) (sqlitegen.Card, error) {
	r, err := a.q.GetCardByNumber(ctx, pggen.GetCardByNumberParams(arg))
	return sqlitegen.Card(r), err
}

func (a *pgQuerier) GetColumn(ctx context.Context, arg string) (sqlitegen.BoardColumn, error) {
	r, err := a.q.GetColumn(ctx, arg)
	return sqlitegen.BoardColumn(r), err
}

func (a *pgQuerier) GetJob(ctx context.Context, arg string) (sqlitegen.Job, error) {
	r, err := a.q.GetJob(ctx, arg)
	return sqlitegen.Job(r), err
}

func (a *pgQuerier) GetLabel(ctx context.Context, arg string) (sqlitegen.Label, error) {
	r, err := a.q.GetLabel(ctx, arg)
	return sqlitegen.Label(r), err
}

func (a *pgQuerier) GetProject(ctx context.Context, arg string) (sqlitegen.Project, error) {
	r, err := a.q.GetProject(ctx, arg)
	return sqlitegen.Project(r), err
}

func (a *pgQuerier) GetProjectByKey(ctx context.Context, arg sqlitegen.GetProjectByKeyParams) (sqlitegen.Project, error) {
	r, err := a.q.GetProjectByKey(ctx, pggen.GetProjectByKeyParams(arg))
	return sqlitegen.Project(r), err
}

func (a *pgQuerier) GetReceipt(ctx context.Context, arg sqlitegen.GetReceiptParams) (sqlitegen.CommandReceipt, error) {
	r, err := a.q.GetReceipt(ctx, pggen.GetReceiptParams(arg))
	return sqlitegen.CommandReceipt(r), err
}

func (a *pgQuerier) GetUser(ctx context.Context, arg string) (sqlitegen.AppUser, error) {
	r, err := a.q.GetUser(ctx, arg)
	return sqlitegen.AppUser(r), err
}

func (a *pgQuerier) GetUserByEmail(ctx context.Context, arg sqlitegen.GetUserByEmailParams) (sqlitegen.AppUser, error) {
	r, err := a.q.GetUserByEmail(ctx, pggen.GetUserByEmailParams(arg))
	return sqlitegen.AppUser(r), err
}

func (a *pgQuerier) GetWorkspace(ctx context.Context, arg string) (sqlitegen.Workspace, error) {
	r, err := a.q.GetWorkspace(ctx, arg)
	return sqlitegen.Workspace(r), err
}

func (a *pgQuerier) GetWorkspaceBySlug(ctx context.Context, arg string) (sqlitegen.Workspace, error) {
	r, err := a.q.GetWorkspaceBySlug(ctx, arg)
	return sqlitegen.Workspace(r), err
}

func (a *pgQuerier) GetWorkspaceMember(ctx context.Context, arg sqlitegen.GetWorkspaceMemberParams) (sqlitegen.WorkspaceMember, error) {
	r, err := a.q.GetWorkspaceMember(ctx, pggen.GetWorkspaceMemberParams(arg))
	return sqlitegen.WorkspaceMember(r), err
}

func (a *pgQuerier) InsertEvent(ctx context.Context, arg sqlitegen.InsertEventParams) error {
	return a.q.InsertEvent(ctx, pggen.InsertEventParams(arg))
}

func (a *pgQuerier) InsertJob(ctx context.Context, arg sqlitegen.InsertJobParams) error {
	return a.q.InsertJob(ctx, pggen.InsertJobParams(arg))
}

func (a *pgQuerier) InsertReceipt(ctx context.Context, arg sqlitegen.InsertReceiptParams) error {
	return a.q.InsertReceipt(ctx, pggen.InsertReceiptParams(arg))
}

func (a *pgQuerier) LastPositionInColumn(ctx context.Context, arg string) (string, error) {
	r, err := a.q.LastPositionInColumn(ctx, arg)
	return r, err
}

func (a *pgQuerier) LeaseJobs(ctx context.Context, arg sqlitegen.LeaseJobsParams) ([]sqlitegen.Job, error) {
	rs, err := a.q.LeaseJobs(ctx, pggen.LeaseJobsParams(arg))
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Job, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Job(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListCardAssigneeIDs(ctx context.Context, arg string) ([]string, error) {
	r, err := a.q.ListCardAssigneeIDs(ctx, arg)
	return r, err
}

func (a *pgQuerier) ListCardLabelIDs(ctx context.Context, arg string) ([]string, error) {
	r, err := a.q.ListCardLabelIDs(ctx, arg)
	return r, err
}

func (a *pgQuerier) ListCardsByBoard(ctx context.Context, arg string) ([]sqlitegen.Card, error) {
	rs, err := a.q.ListCardsByBoard(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Card, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Card(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListCardsByColumn(ctx context.Context, arg string) ([]sqlitegen.Card, error) {
	rs, err := a.q.ListCardsByColumn(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Card, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Card(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListColumns(ctx context.Context, arg string) ([]sqlitegen.BoardColumn, error) {
	rs, err := a.q.ListColumns(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.BoardColumn, len(rs))
	for i := range rs {
		out[i] = sqlitegen.BoardColumn(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListComments(ctx context.Context, arg string) ([]sqlitegen.Comment, error) {
	rs, err := a.q.ListComments(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Comment, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Comment(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListEventsByCard(ctx context.Context, arg sqlitegen.ListEventsByCardParams) ([]sqlitegen.Event, error) {
	rs, err := a.q.ListEventsByCard(ctx, pggen.ListEventsByCardParams(arg))
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Event, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Event(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListEventsSince(ctx context.Context, arg sqlitegen.ListEventsSinceParams) ([]sqlitegen.Event, error) {
	rs, err := a.q.ListEventsSince(ctx, pggen.ListEventsSinceParams(arg))
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Event, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Event(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListJobsByState(ctx context.Context, arg sqlitegen.ListJobsByStateParams) ([]sqlitegen.Job, error) {
	rs, err := a.q.ListJobsByState(ctx, pggen.ListJobsByStateParams(arg))
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Job, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Job(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListLabels(ctx context.Context, arg string) ([]sqlitegen.Label, error) {
	rs, err := a.q.ListLabels(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Label, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Label(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListProjectMembers(ctx context.Context, arg string) ([]sqlitegen.ProjectMember, error) {
	rs, err := a.q.ListProjectMembers(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.ProjectMember, len(rs))
	for i := range rs {
		out[i] = sqlitegen.ProjectMember(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListProjectMembershipsForUser(ctx context.Context, arg string) ([]sqlitegen.ProjectMember, error) {
	rs, err := a.q.ListProjectMembershipsForUser(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.ProjectMember, len(rs))
	for i := range rs {
		out[i] = sqlitegen.ProjectMember(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) ListProjects(ctx context.Context, arg string) ([]sqlitegen.Project, error) {
	rs, err := a.q.ListProjects(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]sqlitegen.Project, len(rs))
	for i := range rs {
		out[i] = sqlitegen.Project(rs[i])
	}
	return out, nil
}

func (a *pgQuerier) MoveCard(ctx context.Context, arg sqlitegen.MoveCardParams) (sqlitegen.Card, error) {
	r, err := a.q.MoveCard(ctx, pggen.MoveCardParams(arg))
	return sqlitegen.Card(r), err
}

func (a *pgQuerier) NextCardNumber(ctx context.Context, arg sqlitegen.NextCardNumberParams) (int64, error) {
	r, err := a.q.NextCardNumber(ctx, pggen.NextCardNumberParams(arg))
	return r, err
}

func (a *pgQuerier) NextPositionAfter(ctx context.Context, arg sqlitegen.NextPositionAfterParams) (string, error) {
	r, err := a.q.NextPositionAfter(ctx, pggen.NextPositionAfterParams(arg))
	return r, err
}

func (a *pgQuerier) NextSeq(ctx context.Context, arg string) (int64, error) {
	r, err := a.q.NextSeq(ctx, arg)
	return r, err
}

func (a *pgQuerier) PrevPositionBefore(ctx context.Context, arg sqlitegen.PrevPositionBeforeParams) (string, error) {
	r, err := a.q.PrevPositionBefore(ctx, pggen.PrevPositionBeforeParams(arg))
	return r, err
}

func (a *pgQuerier) RemoveCardAssignee(ctx context.Context, arg sqlitegen.RemoveCardAssigneeParams) error {
	return a.q.RemoveCardAssignee(ctx, pggen.RemoveCardAssigneeParams(arg))
}

func (a *pgQuerier) RemoveCardLabel(ctx context.Context, arg sqlitegen.RemoveCardLabelParams) error {
	return a.q.RemoveCardLabel(ctx, pggen.RemoveCardLabelParams(arg))
}

func (a *pgQuerier) RetryJob(ctx context.Context, arg sqlitegen.RetryJobParams) error {
	return a.q.RetryJob(ctx, pggen.RetryJobParams(arg))
}

func (a *pgQuerier) SetCardArchived(ctx context.Context, arg sqlitegen.SetCardArchivedParams) (sqlitegen.Card, error) {
	r, err := a.q.SetCardArchived(ctx, pggen.SetCardArchivedParams(arg))
	return sqlitegen.Card(r), err
}

func (a *pgQuerier) TouchCard(ctx context.Context, arg sqlitegen.TouchCardParams) (sqlitegen.Card, error) {
	r, err := a.q.TouchCard(ctx, pggen.TouchCardParams(arg))
	return sqlitegen.Card(r), err
}

func (a *pgQuerier) UpdateCardFields(ctx context.Context, arg sqlitegen.UpdateCardFieldsParams) (sqlitegen.Card, error) {
	r, err := a.q.UpdateCardFields(ctx, pggen.UpdateCardFieldsParams(arg))
	return sqlitegen.Card(r), err
}

func (a *pgQuerier) UpsertProjectMember(ctx context.Context, arg sqlitegen.UpsertProjectMemberParams) error {
	return a.q.UpsertProjectMember(ctx, pggen.UpsertProjectMemberParams(arg))
}

func (a *pgQuerier) UpsertWorkspaceMember(ctx context.Context, arg sqlitegen.UpsertWorkspaceMemberParams) error {
	return a.q.UpsertWorkspaceMember(ctx, pggen.UpsertWorkspaceMemberParams(arg))
}
