// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: card.sql

package pggen

import (
	"context"
	"database/sql"
)

const countCardsInColumn = `-- name: CountCardsInColumn :one
SELECT count(*) FROM card WHERE column_id = $1 AND workspace_id = $2 AND archived_at IS NULL
`

type CountCardsInColumnParams struct {
	ColumnID    string
	WorkspaceID string
}

func (q *Queries) CountCardsInColumn(ctx context.Context, arg CountCardsInColumnParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCardsInColumn, arg.ColumnID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO card (id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, 1, $12, $13)
RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at
`

type CreateCardParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	BoardID     string
	ColumnID    string
	Number      int64
	Title       string
	Description string
	Position    string
	DueDate     sql.NullInt64
	CreatedBy   string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.BoardID,
		arg.ColumnID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Position,
		arg.DueDate,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.TypeID,
		&i.ParentID,
		&i.Priority,
		&i.Estimate,
		&i.StartDate,
		&i.Resolution,
		&i.IterationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const firstPositionInColumn = `-- name: FirstPositionInColumn :one
SELECT position FROM card WHERE column_id = $1 AND workspace_id = $2 ORDER BY position ASC LIMIT 1
`

type FirstPositionInColumnParams struct {
	ColumnID    string
	WorkspaceID string
}

func (q *Queries) FirstPositionInColumn(ctx context.Context, arg FirstPositionInColumnParams) (string, error) {
	row := q.db.QueryRowContext(ctx, firstPositionInColumn, arg.ColumnID, arg.WorkspaceID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const getCard = `-- name: GetCard :one
SELECT id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at FROM card WHERE id = $1 AND workspace_id = $2
`

type GetCardParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCard, arg.ID, arg.WorkspaceID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.TypeID,
		&i.ParentID,
		&i.Priority,
		&i.Estimate,
		&i.StartDate,
		&i.Resolution,
		&i.IterationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardByNumber = `-- name: GetCardByNumber :one
SELECT id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at FROM card WHERE project_id = $1 AND workspace_id = $2 AND number = $3
`

type GetCardByNumberParams struct {
	ProjectID   string
	WorkspaceID string
	Number      int64
}

func (q *Queries) GetCardByNumber(ctx context.Context, arg GetCardByNumberParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByNumber, arg.ProjectID, arg.WorkspaceID, arg.Number)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.TypeID,
		&i.ParentID,
		&i.Priority,
		&i.Estimate,
		&i.StartDate,
		&i.Resolution,
		&i.IterationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastPositionInColumn = `-- name: LastPositionInColumn :one
SELECT position FROM card WHERE column_id = $1 AND workspace_id = $2 ORDER BY position DESC LIMIT 1
`

type LastPositionInColumnParams struct {
	ColumnID    string
	WorkspaceID string
}

func (q *Queries) LastPositionInColumn(ctx context.Context, arg LastPositionInColumnParams) (string, error) {
	row := q.db.QueryRowContext(ctx, lastPositionInColumn, arg.ColumnID, arg.WorkspaceID)
	var position string
	err := row.Scan(&position)
	return position, err
}

const listCardsByBoard = `-- name: ListCardsByBoard :many
SELECT id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at FROM card WHERE board_id = $1 AND workspace_id = $2 AND archived_at IS NULL ORDER BY column_id, position
`

type ListCardsByBoardParams struct {
	BoardID     string
	WorkspaceID string
}

func (q *Queries) ListCardsByBoard(ctx context.Context, arg ListCardsByBoardParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByBoard, arg.BoardID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.BoardID,
			&i.ColumnID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.Version,
			&i.TypeID,
			&i.ParentID,
			&i.Priority,
			&i.Estimate,
			&i.StartDate,
			&i.Resolution,
			&i.IterationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardsByColumn = `-- name: ListCardsByColumn :many
SELECT id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at FROM card WHERE column_id = $1 AND workspace_id = $2 AND archived_at IS NULL ORDER BY position
`

type ListCardsByColumnParams struct {
	ColumnID    string
	WorkspaceID string
}

func (q *Queries) ListCardsByColumn(ctx context.Context, arg ListCardsByColumnParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, listCardsByColumn, arg.ColumnID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Card{}
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.BoardID,
			&i.ColumnID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.CreatedBy,
			&i.CompletedAt,
			&i.ArchivedAt,
			&i.Version,
			&i.TypeID,
			&i.ParentID,
			&i.Priority,
			&i.Estimate,
			&i.StartDate,
			&i.Resolution,
			&i.IterationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCard = `-- name: MoveCard :one

UPDATE card SET column_id = $1, position = $2, completed_at = $3, version = version + 1, updated_at = $4
WHERE id = $5 AND workspace_id = $6 AND version = $7 RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at
`

type MoveCardParams struct {
	ColumnID    string
	Position    string
	CompletedAt sql.NullInt64
	UpdatedAt   int64
	ID          string
	WorkspaceID string
	Version     int64
}

// Every versioned update carries "AND version = @version": on Postgres
// READ COMMITTED two transactions can both read version 1, so the check
// must be in the UPDATE itself; zero rows means E_CONFLICT.
func (q *Queries) MoveCard(ctx context.Context, arg MoveCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, moveCard,
		arg.ColumnID,
		arg.Position,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.TypeID,
		&i.ParentID,
		&i.Priority,
		&i.Estimate,
		&i.StartDate,
		&i.Resolution,
		&i.IterationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextPositionAfter = `-- name: NextPositionAfter :one
SELECT position FROM card WHERE column_id = $1 AND workspace_id = $2 AND position > $3 ORDER BY position ASC LIMIT 1
`

type NextPositionAfterParams struct {
	ColumnID    string
	WorkspaceID string
	Position    string
}

func (q *Queries) NextPositionAfter(ctx context.Context, arg NextPositionAfterParams) (string, error) {
	row := q.db.QueryRowContext(ctx, nextPositionAfter, arg.ColumnID, arg.WorkspaceID, arg.Position)
	var position string
	err := row.Scan(&position)
	return position, err
}

const prevPositionBefore = `-- name: PrevPositionBefore :one
SELECT position FROM card WHERE column_id = $1 AND workspace_id = $2 AND position < $3 ORDER BY position DESC LIMIT 1
`

type PrevPositionBeforeParams struct {
	ColumnID    string
	WorkspaceID string
	Position    string
}

func (q *Queries) PrevPositionBefore(ctx context.Context, arg PrevPositionBeforeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, prevPositionBefore, arg.ColumnID, arg.WorkspaceID, arg.Position)
	var position string
	err := row.Scan(&position)
	return position, err
}

const setCardArchived = `-- name: SetCardArchived :one
UPDATE card SET archived_at = $1, version = version + 1, updated_at = $2
WHERE id = $3 AND workspace_id = $4 AND version = $5 RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at
`

type SetCardArchivedParams struct {
	ArchivedAt  sql.NullInt64
	UpdatedAt   int64
	ID          string
	WorkspaceID string
	Version     int64
}

func (q *Queries) SetCardArchived(ctx context.Context, arg SetCardArchivedParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, setCardArchived,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.TypeID,
		&i.ParentID,
		&i.Priority,
		&i.Estimate,
		&i.StartDate,
		&i.Resolution,
		&i.IterationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchCard = `-- name: TouchCard :one
UPDATE card SET version = version + 1, updated_at = $1
WHERE id = $2 AND workspace_id = $3 AND version = $4 RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at
`

type TouchCardParams struct {
	UpdatedAt   int64
	ID          string
	WorkspaceID string
	Version     int64
}

func (q *Queries) TouchCard(ctx context.Context, arg TouchCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, touchCard,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.TypeID,
		&i.ParentID,
		&i.Priority,
		&i.Estimate,
		&i.StartDate,
		&i.Resolution,
		&i.IterationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCardFields = `-- name: UpdateCardFields :one
UPDATE card SET title = $1, description = $2, due_date = $3, version = version + 1, updated_at = $4
WHERE id = $5 AND workspace_id = $6 AND version = $7 RETURNING id, workspace_id, project_id, board_id, column_id, number, title, description, position, due_date, created_by, completed_at, archived_at, version, type_id, parent_id, priority, estimate, start_date, resolution, iteration_id, created_at, updated_at
`

type UpdateCardFieldsParams struct {
	Title       string
	Description string
	DueDate     sql.NullInt64
	UpdatedAt   int64
	ID          string
	WorkspaceID string
	Version     int64
}

func (q *Queries) UpdateCardFields(ctx context.Context, arg UpdateCardFieldsParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, updateCardFields,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.UpdatedAt,
		arg.ID,
		arg.WorkspaceID,
		arg.Version,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.BoardID,
		&i.ColumnID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.CreatedBy,
		&i.CompletedAt,
		&i.ArchivedAt,
		&i.Version,
		&i.TypeID,
		&i.ParentID,
		&i.Priority,
		&i.Estimate,
		&i.StartDate,
		&i.Resolution,
		&i.IterationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
