// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package pggen

import (
	"context"
	"database/sql"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comment (id, workspace_id, card_id, author_id, body, via_token_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, card_id, author_id, body, via_token_id, edited_at, deleted_at, created_at, updated_at
`

type CreateCommentParams struct {
	ID          string
	WorkspaceID string
	CardID      string
	AuthorID    string
	Body        string
	ViaTokenID  sql.NullString
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.ID,
		arg.WorkspaceID,
		arg.CardID,
		arg.AuthorID,
		arg.Body,
		arg.ViaTokenID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CardID,
		&i.AuthorID,
		&i.Body,
		&i.ViaTokenID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, workspace_id, card_id, author_id, body, via_token_id, edited_at, deleted_at, created_at, updated_at FROM comment WHERE card_id = $1 AND deleted_at IS NULL ORDER BY created_at
`

func (q *Queries) ListComments(ctx context.Context, cardID string) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CardID,
			&i.AuthorID,
			&i.Body,
			&i.ViaTokenID,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
