// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: label.sql

package pggen

import (
	"context"
)

const addCardAssignee = `-- name: AddCardAssignee :exec
INSERT INTO card_assignee (workspace_id, card_id, user_id) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddCardAssigneeParams struct {
	WorkspaceID string
	CardID      string
	UserID      string
}

func (q *Queries) AddCardAssignee(ctx context.Context, arg AddCardAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, addCardAssignee, arg.WorkspaceID, arg.CardID, arg.UserID)
	return err
}

const addCardLabel = `-- name: AddCardLabel :exec
INSERT INTO card_label (workspace_id, card_id, label_id) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddCardLabelParams struct {
	WorkspaceID string
	CardID      string
	LabelID     string
}

func (q *Queries) AddCardLabel(ctx context.Context, arg AddCardLabelParams) error {
	_, err := q.db.ExecContext(ctx, addCardLabel, arg.WorkspaceID, arg.CardID, arg.LabelID)
	return err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO label (id, workspace_id, project_id, name, color, kind, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, 'label', $6, $7)
RETURNING id, workspace_id, project_id, name, color, kind, created_at, updated_at
`

type CreateLabelParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Name        string
	Color       string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLabel = `-- name: GetLabel :one
SELECT id, workspace_id, project_id, name, color, kind, created_at, updated_at FROM label WHERE id = $1
`

func (q *Queries) GetLabel(ctx context.Context, id string) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabel, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardAssigneeIDs = `-- name: ListCardAssigneeIDs :many
SELECT user_id FROM card_assignee WHERE card_id = $1
`

func (q *Queries) ListCardAssigneeIDs(ctx context.Context, cardID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCardAssigneeIDs, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardLabelIDs = `-- name: ListCardLabelIDs :many
SELECT label_id FROM card_label WHERE card_id = $1
`

func (q *Queries) ListCardLabelIDs(ctx context.Context, cardID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listCardLabelIDs, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var label_id string
		if err := rows.Scan(&label_id); err != nil {
			return nil, err
		}
		items = append(items, label_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT id, workspace_id, project_id, name, color, kind, created_at, updated_at FROM label WHERE project_id = $1 ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, projectID string) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCardAssignee = `-- name: RemoveCardAssignee :exec
DELETE FROM card_assignee WHERE card_id = $1 AND user_id = $2
`

type RemoveCardAssigneeParams struct {
	CardID string
	UserID string
}

func (q *Queries) RemoveCardAssignee(ctx context.Context, arg RemoveCardAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, removeCardAssignee, arg.CardID, arg.UserID)
	return err
}

const removeCardLabel = `-- name: RemoveCardLabel :exec
DELETE FROM card_label WHERE card_id = $1 AND label_id = $2
`

type RemoveCardLabelParams struct {
	CardID  string
	LabelID string
}

func (q *Queries) RemoveCardLabel(ctx context.Context, arg RemoveCardLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeCardLabel, arg.CardID, arg.LabelID)
	return err
}
