// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package pggen

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO project (id, workspace_id, key, name, next_card_number, version, created_at, updated_at)
VALUES ($1, $2, $3, $4, 0, 1, $5, $6)
RETURNING id, workspace_id, key, name, next_card_number, estimate_unit, version, archived_at, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string
	WorkspaceID string
	Key         string
	Name        string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.WorkspaceID,
		arg.Key,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.NextCardNumber,
		&i.EstimateUnit,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, workspace_id, key, name, next_card_number, estimate_unit, version, archived_at, created_at, updated_at FROM project WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.NextCardNumber,
		&i.EstimateUnit,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, workspace_id, key, name, next_card_number, estimate_unit, version, archived_at, created_at, updated_at FROM project WHERE workspace_id = $1 AND key = $2
`

type GetProjectByKeyParams struct {
	WorkspaceID string
	Key         string
}

func (q *Queries) GetProjectByKey(ctx context.Context, arg GetProjectByKeyParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, arg.WorkspaceID, arg.Key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Key,
		&i.Name,
		&i.NextCardNumber,
		&i.EstimateUnit,
		&i.Version,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT workspace_id, project_id, user_id, role, created_at FROM project_member WHERE project_id = $1
`

func (q *Queries) ListProjectMembers(ctx context.Context, projectID string) ([]ProjectMember, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembershipsForUser = `-- name: ListProjectMembershipsForUser :many
SELECT workspace_id, project_id, user_id, role, created_at FROM project_member WHERE user_id = $1
`

func (q *Queries) ListProjectMembershipsForUser(ctx context.Context, userID string) ([]ProjectMember, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectMember{}
	for rows.Next() {
		var i ProjectMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, workspace_id, key, name, next_card_number, estimate_unit, version, archived_at, created_at, updated_at FROM project WHERE workspace_id = $1 AND archived_at IS NULL ORDER BY key
`

func (q *Queries) ListProjects(ctx context.Context, workspaceID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Key,
			&i.Name,
			&i.NextCardNumber,
			&i.EstimateUnit,
			&i.Version,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCardNumber = `-- name: NextCardNumber :one
UPDATE project SET next_card_number = next_card_number + 1, updated_at = $1
WHERE id = $2 RETURNING next_card_number
`

type NextCardNumberParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) NextCardNumber(ctx context.Context, arg NextCardNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextCardNumber, arg.UpdatedAt, arg.ID)
	var next_card_number int64
	err := row.Scan(&next_card_number)
	return next_card_number, err
}

const upsertProjectMember = `-- name: UpsertProjectMember :exec
INSERT INTO project_member (workspace_id, project_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = excluded.role
`

type UpsertProjectMemberParams struct {
	WorkspaceID string
	ProjectID   string
	UserID      string
	Role        string
	CreatedAt   int64
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectMember,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}
