// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package pggen

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (id, workspace_id, email, name, kind, password_hash, email_verified_at, locale, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, email, name, kind, password_hash, email_verified_at, locale, disabled_at, deleted_at, anonymized_at, created_at, updated_at
`

type CreateUserParams struct {
	ID              string
	WorkspaceID     string
	Email           sql.NullString
	Name            string
	Kind            string
	PasswordHash    sql.NullString
	EmailVerifiedAt sql.NullInt64
	Locale          string
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Name,
		arg.Kind,
		arg.PasswordHash,
		arg.EmailVerifiedAt,
		arg.Locale,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.Kind,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, workspace_id, email, name, kind, password_hash, email_verified_at, locale, disabled_at, deleted_at, anonymized_at, created_at, updated_at FROM app_user WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.Kind,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, workspace_id, email, name, kind, password_hash, email_verified_at, locale, disabled_at, deleted_at, anonymized_at, created_at, updated_at FROM app_user WHERE workspace_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	WorkspaceID string
	Email       sql.NullString
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.WorkspaceID, arg.Email)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Name,
		&i.Kind,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.Locale,
		&i.DisabledAt,
		&i.DeletedAt,
		&i.AnonymizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, created_at FROM workspace_member WHERE workspace_id = $1 AND user_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const upsertWorkspaceMember = `-- name: UpsertWorkspaceMember :exec
INSERT INTO workspace_member (workspace_id, user_id, role, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (workspace_id, user_id) DO UPDATE SET role = excluded.role
`

type UpsertWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
	Role        string
	CreatedAt   int64
}

func (q *Queries) UpsertWorkspaceMember(ctx context.Context, arg UpsertWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}
